### ISSUE TITLE
Сорри что сюда))

### ISSUE THREAD

**Issue by shimprog** [WhidRubeld/expo-cache-manager#1]
Планируешь обновлять https://www.npmjs.com/package/@appomart/react-native-appmetrica/v/1.0.0?

А  то на новой sdk expo отваливается)))
A problem occurred configuring project ':appomart_react-native-appmetrica'.
[stderr] 
> Could not set unknown property 'classifier' for task ':appomart_react-native-appmetrica:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

**Comment by shimprog** [comment]
Обновишь в щечку поцелую)

**Comment by whidrubeld** [comment]
Постараюсь на неделе сделать
